/** @format */

export interface StateInfo {
  id: number;
  state: string;
  code: string;
}

export const US_STATES: StateInfo[] = [
  { id: 1, state: "Alabama", code: "AL" },
  { id: 2, state: "Alaska", code: "AK" },
  { id: 3, state: "Arizona", code: "AZ" },
  { id: 4, state: "Arkansas", code: "AR" },
  { id: 5, state: "California", code: "CA" },
  { id: 6, state: "Colorado", code: "CO" },
  { id: 7, state: "Connecticut", code: "CT" },
  { id: 8, state: "Delaware", code: "DE" },
  { id: 9, state: "Florida", code: "FL" },
  { id: 10, state: "Georgia", code: "GA" },
  { id: 11, state: "Hawaii", code: "HI" },
  { id: 12, state: "Idaho", code: "ID" },
  { id: 13, state: "Illinois", code: "IL" },
  { id: 14, state: "Indiana", code: "IN" },
  { id: 15, state: "Iowa", code: "IA" },
  { id: 16, state: "Kansas", code: "KS" },
  { id: 17, state: "Kentucky", code: "KY" },
  { id: 18, state: "Louisiana", code: "LA" },
  { id: 19, state: "Maine", code: "ME" },
  { id: 20, state: "Maryland", code: "MD" },
  { id: 21, state: "Massachusetts", code: "MA" },
  { id: 22, state: "Michigan", code: "MI" },
  { id: 23, state: "Minnesota", code: "MN" },
  { id: 24, state: "Mississippi", code: "MS" },
  { id: 25, state: "Missouri", code: "MO" },
  { id: 26, state: "Montana", code: "MT" },
  { id: 27, state: "Nebraska", code: "NE" },
  { id: 28, state: "Nevada", code: "NV" },
  { id: 29, state: "New Hampshire", code: "NH" },
  { id: 30, state: "New Jersey", code: "NJ" },
  { id: 31, state: "New Mexico", code: "NM" },
  { id: 32, state: "New York", code: "NY" },
  { id: 33, state: "North Carolina", code: "NC" },
  { id: 34, state: "North Dakota", code: "ND" },
  { id: 35, state: "Ohio", code: "OH" },
  { id: 36, state: "Oklahoma", code: "OK" },
  { id: 37, state: "Oregon", code: "OR" },
  { id: 38, state: "Pennsylvania", code: "PA" },
  { id: 39, state: "Rhode Island", code: "RI" },
  { id: 40, state: "South Carolina", code: "SC" },
  { id: 41, state: "South Dakota", code: "SD" },
  { id: 42, state: "Tennessee", code: "TN" },
  { id: 43, state: "Texas", code: "TX" },
  { id: 44, state: "Utah", code: "UT" },
  { id: 45, state: "Vermont", code: "VT" },
  { id: 46, state: "Virginia", code: "VA" },
  { id: 47, state: "Washington", code: "WA" },
  { id: 48, state: "West Virginia", code: "WV" },
  { id: 49, state: "Wisconsin", code: "WI" },
  { id: 50, state: "Wyoming", code: "WY" },
];
